services:
  postgres:
    image: postgres:16-alpine
    platform: linux/arm64
    environment:
      POSTGRES_USER: pixelart
      POSTGRES_PASSWORD: pixelart
      POSTGRES_DB: pixelart
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    platform: linux/arm64
    ports: ["6379:6379"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]
  minio:
    image: minio/minio:latest
    platform: linux/arm64
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - miniodata:/data
volumes:
  pgdata: {}
  miniodata: {}
